<a href="https://colab.research.google.com/github/Davron030901/Pandas/blob/main/Missing_Data_Handling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
Missing data'ni aniqlash
NaN qiymatlarni to'ldirish (fillna, interpolate)
Missing values'ni o'chirish
NumPy vs Pandas yondashuvlari

In [2]:
import pandas as pd
import numpy as np

In [3]:
arr = np.array([1, 2, np.nan, 4, 5])
df = pd.DataFrame({'A': [1, np.nan, 3, None, 5]})

In [4]:
data = [1, 2, None, 4]

Aniqlash

In [7]:
pd.isna(df)

       A
0  False
1   True
2  False
3   True
4  False

In [8]:
df.isna()

       A
0  False
1   True
2  False
3   True
4  False

In [11]:
np.isnan(arr)

array([False, False,  True, False, False])

To'ldirish

In [12]:
df.fillna(0)

     A
0  1.0
1  0.0
2  3.0
3  0.0
4  5.0

In [13]:
df.fillna(df.mean())

     A
0  1.0
1  3.0
2  3.0
3  3.0
4  5.0

In [15]:
df.fillna(method='ffill')

/tmp/ipykernel_409/1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

     A
0  1.0
1  1.0
2  3.0
3  3.0
4  5.0

In [16]:
df.interpolate()

     A
0  1.0
1  2.0
2  3.0
3  4.0
4  5.0

O'chirish

In [17]:
df.dropna()

     A
0  1.0
2  3.0
4  5.0

In [18]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

```
NumPy vs Pandas:

NumPy: np.nan, np.isnan(), manual handling
Pandas: NaN, isna(), auto methods