<a href="https://colab.research.google.com/github/Davron030901/Pandas/blob/main/Missing_Data_Handling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
Missing data'ni aniqlash
NaN qiymatlarni to'ldirish (fillna, interpolate)
Missing values'ni o'chirish
NumPy vs Pandas yondashuvlari

In [71]:
import pandas as pd
import numpy as np

In [72]:
arr = np.array([1, 2, np.nan, 4, 5])
df = pd.DataFrame({'A': [1, np.nan, 3, None, 5]})

In [73]:
data = [1, 2, None, 4]

Aniqlash

In [74]:
pd.isna(df)

       A
0  False
1   True
2  False
3   True
4  False

In [75]:
df.isna()

       A
0  False
1   True
2  False
3   True
4  False

In [76]:
np.isnan(arr)

array([False, False,  True, False, False])

To'ldirish

In [77]:
df.fillna(0)

     A
0  1.0
1  0.0
2  3.0
3  0.0
4  5.0

In [78]:
df.fillna(df.mean())

     A
0  1.0
1  3.0
2  3.0
3  3.0
4  5.0

In [79]:
df.fillna(method='ffill')

/tmp/ipykernel_779/1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

     A
0  1.0
1  1.0
2  3.0
3  3.0
4  5.0

In [80]:
df.interpolate()

     A
0  1.0
1  2.0
2  3.0
3  4.0
4  5.0

O'chirish

In [81]:
df.dropna()

     A
0  1.0
2  3.0
4  5.0

In [82]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

```
NumPy vs Pandas:

NumPy: np.nan, np.isnan(), manual handling
Pandas: NaN, isna(), auto methods

#Temperature Data Cleaning (30%)

In [83]:
temperatures = pd.Series([23.5, np.nan, 25.1, np.nan, 24.8, 26.3, np.nan, 25.9])
count_nan = temperatures.isna().sum()
print(count_nan)
clean_data = temperatures.dropna()
print(clean_data)

3
0    23.5
2    25.1
4    24.8
5    26.3
7    25.9
dtype: float64

In [84]:
forward_fill = temperatures.fillna(method='ffill')
print(forward_fill)

0    23.5
1    23.5
2    25.1
3    25.1
4    24.8
5    26.3
6    26.3
7    25.9
dtype: float64

/tmp/ipykernel_779/1844348188.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  forward_fill = temperatures.fillna(method='ffill')

In [85]:
print(forward_fill.mean())

25.0625

In [86]:
fill_temperatures = temperatures.fillna(temperatures.mean())
print(fill_temperatures)

0    23.50
1    25.12
2    25.10
3    25.12
4    24.80
5    26.30
6    25.12
7    25.90
dtype: float64

# Sales Data Interpolation

In [87]:
sales_data = {
    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
    'Sales': [150, np.nan, 180, np.nan, np.nan, 220],
    'Profit': [45, 50, np.nan, 60, 65, np.nan]
}

df = pd.DataFrame(sales_data)
print(df)

  Month  Sales  Profit
0   Jan  150.0    45.0
1   Feb    NaN    50.0
2   Mar  180.0     NaN
3   Apr    NaN    60.0
4   May    NaN    65.0
5   Jun  220.0     NaN

In [88]:
each_column_nan = df.isna().sum()
print(each_column_nan)

Month     0
Sales     3
Profit    2
dtype: int64

In [89]:
df['Sales'] = df['Sales'].fillna(df['Sales'].interpolate(method='linear'))
print(df['Sales'])

0    150.000000
1    165.000000
2    180.000000
3    193.333333
4    206.666667
5    220.000000
Name: Sales, dtype: float64

In [90]:
df['Profit'] = df['Profit'].fillna(df['Profit'].mean())
print(df['Profit'])

0    45.0
1    50.0
2    55.0
3    60.0
4    65.0
5    55.0
Name: Profit, dtype: float64

In [91]:
print(df)

  Month       Sales  Profit
0   Jan  150.000000    45.0
1   Feb  165.000000    50.0
2   Mar  180.000000    55.0
3   Apr  193.333333    60.0
4   May  206.666667    65.0
5   Jun  220.000000    55.0

#Student Grades Analysis

In [92]:
grades = {
    'Student': ['Ali', 'Vali', 'Guli', 'Sami', 'Nuri'],
    'Math': [85, np.nan, 92, 78, np.nan],
    'Physics': [np.nan, 88, 91, np.nan, 86],
    'Chemistry': [80, 85, np.nan, 90, 88]
}

df = pd.DataFrame(grades)
print(df)

  Student  Math  Physics  Chemistry
0     Ali  85.0      NaN       80.0
1    Vali   NaN     88.0       85.0
2    Guli  92.0     91.0        NaN
3    Sami  78.0      NaN       90.0
4    Nuri   NaN     86.0       88.0

In [93]:
each_student_missing = df.isna().sum(axis=1)
print(each_student_missing)

0    1
1    1
2    1
3    1
4    1
dtype: int64

In [94]:
for i in range(len(df)):
    if each_student_missing[i] >= 2:
        df.drop(i, inplace=True)
print(df)

  Student  Math  Physics  Chemistry
0     Ali  85.0      NaN       80.0
1    Vali   NaN     88.0       85.0
2    Guli  92.0     91.0        NaN
3    Sami  78.0      NaN       90.0
4    Nuri   NaN     86.0       88.0

In [95]:
df['Chemistry'] = df['Chemistry'].fillna(df['Chemistry'].mean())
df['Math'] = df['Math'].fillna(df['Math'].mean())
df['Physics'] = df['Physics'].fillna(df['Physics'].mean())
print(df)

  Student  Math    Physics  Chemistry
0     Ali  85.0  88.333333      80.00
1    Vali  85.0  88.000000      85.00
2    Guli  92.0  91.000000      85.75
3    Sami  78.0  88.333333      90.00
4    Nuri  85.0  86.000000      88.00

In [101]:
avg_student = df.mean(numeric_only=True, axis=1)
print(avg_student)

0    84.444444
1    86.000000
2    89.583333
3    85.444444
4    86.333333
dtype: float64

In [102]:
add_df = df.assign(Average=avg_student)
print(add_df)

  Student  Math    Physics  Chemistry    Average
0     Ali  85.0  88.333333      80.00  84.444444
1    Vali  85.0  88.000000      85.00  86.000000
2    Guli  92.0  91.000000      85.75  89.583333
3    Sami  78.0  88.333333      90.00  85.444444
4    Nuri  85.0  86.000000      88.00  86.333333