<a href="https://colab.research.google.com/github/Davron030901/Pandas/blob/main/Missing_Data_Handling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
Missing data'ni aniqlash
NaN qiymatlarni to'ldirish (fillna, interpolate)
Missing values'ni o'chirish
NumPy vs Pandas yondashuvlari

In [15]:
import pandas as pd
import numpy as np

In [16]:
arr = np.array([1, 2, np.nan, 4, 5])
df = pd.DataFrame({'A': [1, np.nan, 3, None, 5]})

In [17]:
data = [1, 2, None, 4]

Aniqlash

In [18]:
pd.isna(df)

       A
0  False
1   True
2  False
3   True
4  False

In [19]:
df.isna()

       A
0  False
1   True
2  False
3   True
4  False

In [20]:
np.isnan(arr)

array([False, False,  True, False, False])

To'ldirish

In [21]:
df.fillna(0)

     A
0  1.0
1  0.0
2  3.0
3  0.0
4  5.0

In [22]:
df.fillna(df.mean())

     A
0  1.0
1  3.0
2  3.0
3  3.0
4  5.0

In [23]:
df.fillna(method='ffill')

/tmp/ipykernel_779/1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

     A
0  1.0
1  1.0
2  3.0
3  3.0
4  5.0

In [24]:
df.interpolate()

     A
0  1.0
1  2.0
2  3.0
3  4.0
4  5.0

O'chirish

In [25]:
df.dropna()

     A
0  1.0
2  3.0
4  5.0

In [26]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

```
NumPy vs Pandas:

NumPy: np.nan, np.isnan(), manual handling
Pandas: NaN, isna(), auto methods

#Temperature Data Cleaning (30%)

In [27]:
temperatures = pd.Series([23.5, np.nan, 25.1, np.nan, 24.8, 26.3, np.nan, 25.9])
count_nan = temperatures.isna().sum()
print(count_nan)
clean_data = temperatures.dropna()
print(clean_data)

3
0    23.5
2    25.1
4    24.8
5    26.3
7    25.9
dtype: float64

In [28]:
forward_fill = temperatures.fillna(method='ffill')
print(forward_fill)

0    23.5
1    23.5
2    25.1
3    25.1
4    24.8
5    26.3
6    26.3
7    25.9
dtype: float64

/tmp/ipykernel_779/1844348188.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  forward_fill = temperatures.fillna(method='ffill')

In [29]:
print(forward_fill.mean())

25.0625

In [30]:
fill_temperatures = temperatures.fillna(temperatures.mean())
print(fill_temperatures)

0    23.50
1    25.12
2    25.10
3    25.12
4    24.80
5    26.30
6    25.12
7    25.90
dtype: float64

# Sales Data Interpolation

In [31]:
sales_data = {
    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
    'Sales': [150, np.nan, 180, np.nan, np.nan, 220],
    'Profit': [45, 50, np.nan, 60, 65, np.nan]
}

df = pd.DataFrame(sales_data)
print(df)

  Month  Sales  Profit
0   Jan  150.0    45.0
1   Feb    NaN    50.0
2   Mar  180.0     NaN
3   Apr    NaN    60.0
4   May    NaN    65.0
5   Jun  220.0     NaN